export default {
"shellSkin":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAAGCAIAAACaUPOvAAAALklEQVQIHWO8MtmKAS9gkVHjw6uAgYWB6R0BFVdPnieg4u9f/AoYWG7c+I1fCQDP6QoJa6X/jQAAAABJRU5ErkJggg==",
"shellSkin.pivotPoint": "(0.5, 0.5)",
"shellSkin.pixelPerUnit": "100",
"id": "45ACP",
"uiName": "45ACP",
"caliberName": "11.43x23",
"iconButtonSprite":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEQAAAAZCAYAAACIA4ibAAACGUlEQVRYCe2Z303DMBDG70IDVEKkAgZAYgE2oExAmYCMABv0hWc6AZRXXugIYYN2AKTwzkNASIWmxHznxI6RGIDWduXc2a6q3K+f/+TCD7fXiurCr0VBB0lPWnfElNbd//rKO+/PzQ2aMOqmYkUbHFFVKVIIhtDe3I5tMIvPUvtuX/lVUsd8AzBOGj9dERgEGC6FHPcv1ZQJnCyKePZdmS6icr6kuNvRcMR3S7wVt0BYcaYHAXM1Cx/ivqXqgnj6EAeKyiGPDI4GBBhv8Ekr5I9YIxlc78KHiDsFoAkUUaDeIN5Epoo7XQwDD4CYUK29LOflFAo5M+uIGZG2j0AQP1QDxaA+opEYIKIYT4EYBDRYzMvMheI7EGyofIx1ZSw7jlTvgTRaGVCkTlADEDt5KhoSziv2YGYHvHW4jzNKEqaMIwAc3Y8DEAeIuAGIAyQiLsIa0gDBM3GBh8BZAGIVwvLwF3YZy6PDwwDE0qARL9VLAAICWDumMFeGje9ryGSzG6cGhlhPt12VI+c6QD0HgzeTFxHro0JGcTceCghUXUzmTGwLRKmsGe83dk2Mypg5gxoyBPREVZ1INaoQCMiJEKaOthbI/l7vVBL2+FwgRzBeDRr2T5RXDXnEbda9BeBE0sCQHgEh+Q/tA4axANL+qLBDovpesMBP9bf+8eVj9+i0fS/zx41qAM6bCuQ7fimkFovOwGullN/0A2SjwmkvcNieAAAAAElFTkSuQmCC",
"iconButtonSprite.pivotPoint": "(0.5, 0.5)",
"iconButtonSprite.pixelPerUnit": "130",
"iconListSprite":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEQAAAAZCAYAAACIA4ibAAACGUlEQVRYCe2Z303DMBDG70IDVEKkAgZAYgE2oExAmYCMABv0hWc6AZRXXugIYYN2AKTwzkNASIWmxHznxI6RGIDWduXc2a6q3K+f/+TCD7fXiurCr0VBB0lPWnfElNbd//rKO+/PzQ2aMOqmYkUbHFFVKVIIhtDe3I5tMIvPUvtuX/lVUsd8AzBOGj9dERgEGC6FHPcv1ZQJnCyKePZdmS6icr6kuNvRcMR3S7wVt0BYcaYHAXM1Cx/ivqXqgnj6EAeKyiGPDI4GBBhv8Ekr5I9YIxlc78KHiDsFoAkUUaDeIN5Epoo7XQwDD4CYUK29LOflFAo5M+uIGZG2j0AQP1QDxaA+opEYIKIYT4EYBDRYzMvMheI7EGyofIx1ZSw7jlTvgTRaGVCkTlADEDt5KhoSziv2YGYHvHW4jzNKEqaMIwAc3Y8DEAeIuAGIAyQiLsIa0gDBM3GBh8BZAGIVwvLwF3YZy6PDwwDE0qARL9VLAAICWDumMFeGje9ryGSzG6cGhlhPt12VI+c6QD0HgzeTFxHro0JGcTceCghUXUzmTGwLRKmsGe83dk2Mypg5gxoyBPREVZ1INaoQCMiJEKaOthbI/l7vVBL2+FwgRzBeDRr2T5RXDXnEbda9BeBE0sCQHgEh+Q/tA4axANL+qLBDovpesMBP9bf+8eVj9+i0fS/zx41qAM6bCuQ7fimkFovOwGullN/0A2SjwmkvcNieAAAAAElFTkSuQmCC",
"iconListSprite.pivotPoint": "(0.5, 0.5)",
"iconListSprite.pixelPerUnit": "130",
"totalStockNum": -1,
"bullets": 1,
"angleRandom": 0,
"angleSpread": 0,
"damage": 2,
"stopPower": 0.05,
"noiseVolume": 1.5,
"impulse": 17,
"velocityMax": 10,
"angularMax": 2000,
"distance": 24,
"penetration": {
  "modeHit": "FIRST",
  "minHits": 1,
  "maxHits": 1,
  "minDist": 0.0,
  "maxDist": 0.0,
  "findExitPoint": true
},
"penetrationDamage": [],
"entityTag": "",
"skillObjectTags": [],
"hitEffects.materials": "EffectHitMaterial[]",
"hitEffects.sounds": "SoundBulletHit[]"
};