weapons.push({
	"arrowSample.WeaponArrow.render": "arrowRender",
	"arrowSample.WeaponArrow.materialBody.bounciness": 0.2,
	"arrowSample.WeaponArrow.materialBody.friction": 1,
	"arrowSample.WeaponArrow.materialBody.frictionCombine": "Mean",
	"arrowSample.WeaponArrow.materialBody.bounceCombine": "Maximum",
	"arrowSample.WeaponArrow.materialBody.name": "skin",
	"arrowSample.WeaponArrow.materialBody.hideFlags": "None",
	"arrowSample.WeaponArrow.speed": 70,
	"arrowSample.WeaponArrow.timerLive": 3,
	"arrowSample.WeaponArrow.scaleGravity": 0,
	"arrowSample.WeaponArrow.floor": -6,
	"arrowSample.WeaponArrow.pointTip": "(-1, 0)",
	"arrowSample.WeaponArrow.pointFrontTip": "(1.24, 0)",
	"arrowSample.WeaponArrow.pointSpriteCheck": "(0.25, 0)",
	"arrowSample.WeaponArrow.angleTipSpeed": 90,
	"arrowSample.WeaponArrow.spriteHit": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIwAAAAICAYAAAAr4RfwAAACG0lEQVRYCe1XTWrCUBCe+C+KBvxZ2iwEQdQqHqC9gNAu3HuE3qA9gkfIEdKdC6Hpxo2b9ACi4k4RFRFF/Ok3kic2RYgUrIsMvMy8me/5hnmfkxepUCgQi9frPWjxqFarwowuFouiJEmP+/1egZPHD4HfcLlcU2gdgU8OAk/b7Zba7TaNx2N2OXJjFchkMiKjV5yXgnPW4HgPh8PU6XRIURTa7XYUjUYPuOFwSFIulyMc9i/CMKJSqbDa8+MSAVF0JKBBcwL9RqNxyXIHe8UKZLNZ3u0jGAw+srFaraYgiQrC1DHtp1Kpn4QxO8wrOswbL7CKSRqr2/a81Wo5HcZ2tf4H6PP5KJlMkizL5Pf7j0nM53Mmzxs6jArnTHSYB4D0I+rEwCuGTtrWScS+ORgMaLlc2l/gIP+1Avw6isViFI/HrXloIIzqAVkMRPjV8WRF8D3kr4Th+4tDGGtlb3fudrvJ4/GcTZAjM4xnK8K8qN7B37PGLpmXSqUi8F/NZvOSZQ72ShXgbgK5TyQSLyDLUyAQkMXW+KMbuNvUMdcwmCd0lkq1Wo3jfX7YFVxyp8Aa6Ez6ZrMxIpGIjgQOG9n9DQd3vQqUy2WxmSGM9Xrdw1C73a4KXz+fz4vQQZ8lDH8SmyJBP7ANn4x2VTT9rHq45/TYCIVCvOkMn2Y8PcpkMjnajnE7FTghCyel4dymo9GoDvtL3F/S6fSvhL8BeTy47nXEQMIAAAAASUVORK5CYII=",
	"arrowSample.WeaponArrow.spriteHit.pivotPoint": "(0.5, 0.5)",
	"arrowSample.WeaponArrow.spriteHit.pixelPerUnit": "50",
	"arrowSample.WeaponArrow.scaleImpulse": 5,
	"arrowSample.WeaponArrow.useGUILayout": true,
	"arrowSample.WeaponArrow.runInEditMode": false,
	"arrowSample.WeaponArrow.enabled": true,
	"arrowSample.WeaponArrow.tag": "Untagged",
	"arrowSample.WeaponArrow.name": "ShotArrowBow",
	"arrowSample.WeaponArrow.hideFlags": "None",
	"arrowSample.arrowRender.Transform.localPosition": "(0, 0, 0)",
	"arrowSample.arrowRender.Transform.localEulerAngles.z": 0,
	"arrowSample.arrowRender.gameObject.SetActive": true,
	"arrowSample.arrowRender.SpriteRenderer.sprite": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIwAAAAICAYAAAAr4RfwAAACG0lEQVRYCe1XTWrCUBCe+C+KBvxZ2iwEQdQqHqC9gNAu3HuE3qA9gkfIEdKdC6Hpxo2b9ACi4k4RFRFF/Ok3kic2RYgUrIsMvMy8me/5hnmfkxepUCgQi9frPWjxqFarwowuFouiJEmP+/1egZPHD4HfcLlcU2gdgU8OAk/b7Zba7TaNx2N2OXJjFchkMiKjV5yXgnPW4HgPh8PU6XRIURTa7XYUjUYPuOFwSFIulyMc9i/CMKJSqbDa8+MSAVF0JKBBcwL9RqNxyXIHe8UKZLNZ3u0jGAw+srFaraYgiQrC1DHtp1Kpn4QxO8wrOswbL7CKSRqr2/a81Wo5HcZ2tf4H6PP5KJlMkizL5Pf7j0nM53Mmzxs6jArnTHSYB4D0I+rEwCuGTtrWScS+ORgMaLlc2l/gIP+1Avw6isViFI/HrXloIIzqAVkMRPjV8WRF8D3kr4Th+4tDGGtlb3fudrvJ4/GcTZAjM4xnK8K8qN7B37PGLpmXSqUi8F/NZvOSZQ72ShXgbgK5TyQSLyDLUyAQkMXW+KMbuNvUMdcwmCd0lkq1Wo3jfX7YFVxyp8Aa6Ez6ZrMxIpGIjgQOG9n9DQd3vQqUy2WxmSGM9Xrdw1C73a4KXz+fz4vQQZ8lDH8SmyJBP7ANn4x2VTT9rHq45/TYCIVCvOkMn2Y8PcpkMjnajnE7FTghCyel4dymo9GoDvtL3F/S6fSvhL8BeTy47nXEQMIAAAAASUVORK5CYII=",
	"arrowSample.arrowRender.SpriteRenderer.sprite.pivotPoint": "(0.5, 0.5)",
	"arrowSample.arrowRender.SpriteRenderer.sprite.pixelPerUnit": "50",
	"arrowSample.arrowRender.SpriteRenderer.sortingOrder": 50,
	"arrowSample.arrowRender.SpriteRenderer.enabled": true,
	"arrowSample.arrowRender.name": "arrowRender",


	"arrowsPerShot": 1,
	"angleScatter": 0,
	"evenlySpread": 0,
	"timeTriggers": 0.6,
	"distHitArrow": 25,
	"id": "arrows",
	"uiName": "arrows",
	"caliberName": "arrows",
	"iconButtonSprite":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACFElEQVRIDaWUPW4CMRCFzbKCkkggJKpQ0qVA1OEI3CBU1Bxhj5AbJBwhNyA1BaSgoiE0NBTZEiQg71n7VmbjDX8jDR6P19+Mh7ELg8HA3Cv7/T5FBEFgCoWCnR+PRxOmKzcYBBwOB7uTYNl0KGjg404mE0OVEJQV+QjOE655T9DpdE726Miukz4FoT/J/hFmBB0Wi8WY6/nh8dUlIjCyfQN0icAP2BdzL5NIT6BslC3nbpbyK2jy/TPAEda68sOOZHNMA2QBmmt0N8F+SUBN14+gY+iX60sDuM4cuwL/ENqHNqFWttutKZfLmkYyNNoAyXHlyxtZ1yEyZ43NZrMx6/XaNBoNGwCMGdyfXJPw9GEcx6ZSYXIXyRDf91arVW+325lSqWRqtZrdCNirjxAuFouTdvN95PhmBDEzSrVa1dISxkgTdwwuLA/3PAE8htoSsSXr9bpY7zKy46X34AQOyKzVakVhGPL0P5h7y8NggY7LSY78geO77nw+H+G9aSJAH5ct5oXz6bkSeeEIYG8qxm/oB98cKmU6nab/KX3/3YNzcAt0fwhst9s2gCqTV6Kr4Ml7ZGPxmWbjqFy+El0FJ1XloY3uSucsV7aLroYT6hPCWa6QtUruws1wt0QMJjhtlehmuIVkuoiZS1iiu+ACcVQXnfhQovT6Y2EG7ULV5zDPS7ZE7g62qX1b4LwJTpjbRS6c9i+0G/JqaJFAVAAAAABJRU5ErkJggg==",
	"iconButtonSprite.pivotPoint": "(0.5, 0.5)",
	"iconButtonSprite.pixelPerUnit": "100",
	"iconListSprite":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIwAAAAICAYAAAAr4RfwAAACG0lEQVRYCe1XTWrCUBCe+C+KBvxZ2iwEQdQqHqC9gNAu3HuE3qA9gkfIEdKdC6Hpxo2b9ACi4k4RFRFF/Ok3kic2RYgUrIsMvMy8me/5hnmfkxepUCgQi9frPWjxqFarwowuFouiJEmP+/1egZPHD4HfcLlcU2gdgU8OAk/b7Zba7TaNx2N2OXJjFchkMiKjV5yXgnPW4HgPh8PU6XRIURTa7XYUjUYPuOFwSFIulyMc9i/CMKJSqbDa8+MSAVF0JKBBcwL9RqNxyXIHe8UKZLNZ3u0jGAw+srFaraYgiQrC1DHtp1Kpn4QxO8wrOswbL7CKSRqr2/a81Wo5HcZ2tf4H6PP5KJlMkizL5Pf7j0nM53Mmzxs6jArnTHSYB4D0I+rEwCuGTtrWScS+ORgMaLlc2l/gIP+1Avw6isViFI/HrXloIIzqAVkMRPjV8WRF8D3kr4Th+4tDGGtlb3fudrvJ4/GcTZAjM4xnK8K8qN7B37PGLpmXSqUi8F/NZvOSZQ72ShXgbgK5TyQSLyDLUyAQkMXW+KMbuNvUMdcwmCd0lkq1Wo3jfX7YFVxyp8Aa6Ez6ZrMxIpGIjgQOG9n9DQd3vQqUy2WxmSGM9Xrdw1C73a4KXz+fz4vQQZ8lDH8SmyJBP7ANn4x2VTT9rHq45/TYCIVCvOkMn2Y8PcpkMjnajnE7FTghCyel4dymo9GoDvtL3F/S6fSvhL8BeTy47nXEQMIAAAAASUVORK5CYII=",
	"iconListSprite.pivotPoint": "(0.5, 0.5)",
	"iconListSprite.pixelPerUnit": "50",
	"totalStockNum": -1,
	"bullets": 1,
	"angleRandom": 0,
	"angleSpread": 0,
	"damage": 7,
	"stopPower": 0.6,
	"noiseVolume": 1,
	"impulse": 25,
	"velocityMax": 15,
	"angularMax": 2000,
	"distance": 4,
	"penetration": {
		"modeHit": "FIRST",
		"minHits": 1,
		"maxHits": 1,
		"minDist": 0.0,
		"maxDist": 0.0,
		"findExitPoint": true
	},
	"penetrationDamage": [],
	"entityTag": "",
	"skillObjectTags": [],
	"hitEffects.materials": "EffectHitMaterial[]",
	"hitEffects.sounds": "SoundBulletHit[]"
});